# Generated by Django 5.0.4 on 2025-04-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='post_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
