# Generated by Django 5.0.4 on 2025-05-16 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_post_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, unique=True)),
                ('df', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tf_idf', models.FloatField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postings', to='documents.document')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postings', to='documents.term')),
            ],
            options={
                'unique_together': {('term', 'document')},
            },
        ),
    ]
