# Generated by Django 5.0.4 on 2025-05-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_term_posting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='post_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
